version: "3"
services:
    migrations:
        image: "flask-by-example:v1"
        command: "manage.py db upgrade"
        environment:
            APP_SETTINGS: config.ProductionConfig
            DATABASE_URL: postgresql://wordcount_dbadmin:$DBPASS@db/wordcount
        depends_on:
            - db
    db:
        image: "postgres:11"
        container_name: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    worker:
        image: "flask-by-example:v1"
        command: "worker.py"
        environment:
            APP_SETTINGS: config.ProductionConfig
            DATABASE_URL: postgresql://wordcount_dbadmin:$DBPASS@db/wordcount
            REDISTOGO_URL: redis://redis:6379
        depends_on:
            - db
            - redis
    app:
        image: "flask-by-example:v1"
        command: "manage.py runserver --host=0.0.0.0"
        ports:
            - "5000:5000"
        environment:
            APP_SETTINGS: config.ProductionConfig
            DATABASE_URL: postgresql://wordcount_dbadmin:$DBPASS@db/wordcount
            REDISTOGO_URL: redis://redis:6379
        depends_on:
            - db
            - redis
volumes:
    dbdata: