apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: migrations
  name: migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrations
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: migrations
    spec:
      containers:
        - args:
            - manage.py
            - db
            - upgrade
          env:
            - name: APP_SETTINGS
              value: config.ProductionConfig
            - name: DATABASE_URL
              value: postgresql://wordcount_dbadmin:@db/wordcount
          image: flask-by-example:v1
          name: migrations
          resources: {}
      restartPolicy: Always
status: {}
